### ISSUE TITLE
mlkit disabled in homebrew, marked "unmaintained"

### ISSUE THREAD

**Issue by cannam** [melsman/mlkit#51] opened 2021-01-13 11:15 UTC
Hello! I've just noticed that Homebrew on Mac now refuses to install MLKit. It says:

```
Error: mlkit has been disabled because it is not maintained upstream!
```

Here's the relevant [Homebrew commit](https://github.com/Homebrew/homebrew-core/commit/58c4eba442da3ca6df0067f31dd54177144d8c14#diff-1d0b98e99b9e44eaf1f337a56411a107c0eb33ea2ecaf4f86c5339bd4432f32d).

I'm wary of just reporting this as a bug in Homebrew, as I don't know what the situation really is - MLKit doesn't look unmaintained to me, and your README still says to get it from Homebrew, but one imagines there must be some reason why this happened. Just wondering whether you know what that might be. Thank you!

**Comment by melsman** [comment] 2021-01-13 11:30
Thanks Chris!

The problem is that there is a bug in MLton that makes it impossible to
build MLKit using MLton's 100220 release. The bug is fixed upstream. The
Homebrew guys asked me to add a patch and create new Homebrew PRs for
smlpkg and mlkit if I want the formulas back into Homebrew. Matthew Fluet
will soon throw a new bug-fix release and I think I will wait for this to
happen before I work on getting mlkit and smlpkg back into Homebrew. In the
meantime, I'm currently working on using github actions to build binary
releases for both macos and linux (currently, only binary releases for
linux are created, but it will be fixed later today).

Best,

Martin

**Comment by melsman** [comment] 2021-01-13 11:32
See https://github.com/Homebrew/homebrew-core/issues/68828

**Comment by melsman** [comment] 2021-01-13 13:08
Binary distributions are now being built and published by github actions:

https://github.com/melsman/mlkit/releases/tag/v4.5.3

**Comment by melsman** [comment] 2021-02-11 08:09
Closing this issue as `mlkit` and `smlpkg` are now back in Homebrew - we should bump the version, however, and make sure that `smltojs` is also part of the install (similar to how we build the binary packages in [.github/workflows/main.yml](https://github.com/melsman/mlkit/blob/master/.github/workflows/main.yml).

**Closed by melsman** 2021-02-11 08:09 UTC
